name: Deploy Frontend to S3
description: Deploy the Frontend with a manual trigger

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: src/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/s3-sync
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          bucket_name: ${{ secrets.AWS_S3_BUCKET }}
